### PR TITLE
Only trigger controller presubmit for changes in config or controllers folder at root

### PR DESCRIPTION
**Pull request by taneyland**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-prow-jobs/pull/24#" title="Author self-approved">taneyland</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-prow-jobs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-prow-jobs/blob/main/OWNERS)~~ [taneyland]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-prow-jobs/pull/24#" title="Author self-approved">taneyland</a>*, *<a href="https://github.com/aws/eks-anywhere-prow-jobs/pull/24#pullrequestreview-762290039" title="LGTM">TerryHowe</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-prow-jobs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-prow-jobs/blob/main/OWNERS)~~ [TerryHowe,taneyland]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Comment by abhay-krishna** [comment]
@taneyland: Updated the `job-config` configmap in namespace `default` at cluster `default` using the following files:
 - key `eks-anywhere-cluster-controller-presubmits.yaml` using file `jobs/aws/eks-anywhere/eks-anywhere-cluster-controller-presubmits.yaml`

<details>

In response to [this](https://github.com/aws/eks-anywhere-prow-jobs/pull/24):

>*Issue #, if available:*
>
>*Description of changes:*
>
>
>By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
>
>
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
