### PR TITLE
Adding prow jobs for generatebundlefile in eks-anywhere-packages

### PR DESCRIPTION
**Pull request by jonahjon**
Signed-off-by: jonahjon <jonahjones094@gmail.com>

*Description of changes:*

Adding Prow jobs for generatebundlefile.

### CODE REVIEW

**Comment by jonahjon** [comment]
Don't merge until 
https://github.com/aws/eks-anywhere-packages/pull/221
https://github.com/aws/eks-anywhere-packages/pull/222
are both in otherwise will get failing tests.

**Review by TerryHowe — COMMENTED** [review]
I assume this can just be closed????

**Pull request merged**
