### PR TITLE
Update integration test ami for e2e presubmit

### PR DESCRIPTION
**Pull request by g-gaston**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
waiting on the pipeline deploy?

**Comment by g-gaston** [comment]
> waiting on the pipeline deploy?

@TerryHowe ready
I needed to update the constants file too, aparently

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Pull request merged**
